FROM golang:1.21-alpine AS builder

RUN apk add --no-cache git gcc musl-dev

WORKDIR /build

COPY amf/go.mod amf/go.sum ./
RUN go mod download

COPY amf/ ./

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o amf ./cmd/

FROM alpine:3.15

LABEL description="Free5GC open source 5G Core Network - AMF" \
    version="Stage 3"

ENV F5GC_MODULE=amf

RUN apk add --no-cache tini

WORKDIR /free5gc
RUN mkdir -p config/ log/ cert/

COPY --from=builder /build/amf ./
COPY --from=builder /build/cert/ ./cert/
COPY --from=builder /build/config/ ./config/

VOLUME [ "/free5gc/config" ]
VOLUME [ "/free5gc/cert" ]

EXPOSE 8000

ENTRYPOINT [ "/sbin/tini", "--" ]
CMD [ "./amf" ]